update pre-commit

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,5 +1,13 @@
 #!/bin/sh
 
+
+TEST=php artisan test
+
+# Run tests for staged files only
+if ! $TEST; then
+  echo "You have errors in your unit test"
+fi
+
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
 
 if [[ "$STAGED_FILES" = "" ]]; then
@@ -39,16 +47,6 @@ if ! $PASS; then
 else
   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
-
-
-TEST=php artisan test
-
-# Run tests for staged files only
-if ! $TEST; then
-  echo "You have errors in your unit test"
-  exit -1
-fi
-
 
 exit $?
 
