update pre-comit

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -2,6 +2,14 @@
 
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")
 
+TEST=php artisan test
+
+# Run tests for staged files only
+if ! $TEST; then
+  echo "You have errors in your unit test"
+  exit 0
+fi
+
 if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
@@ -38,10 +46,6 @@ if ! $PASS; then
   exit 1
 else
   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
-  if ! php artisan test; then
-      echo "You have errors in your unit test"
-    fi
-
 fi
 
 exit $?
